[package]
name = "slice"
version = "0.1.0"
authors = ["Kumar Subramaniam <Kumar.Subramaniam@wnco.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
